### ISSUE TITLE
Error : 'predizer' is not an exported object from 'namespace:captchaReceitaAudio'

### ISSUE THREAD

**Issue by sillasgonzaga** [jtrecenti/cnpjReceita#1]
Executar o comando abaixo resultou no erro do título desta issue.
```

if (!require(devtools)) install.packages('devtools')
devtools::install_github('jtrecenti/cnpjReceita')

library(cnpjReceita)
cnpj <- '00.000.000/0001-91'
d_result <- buscar_cnpj(cnpj, output = 'df')
```

**Comment by jtrecenti** [comment]
Provavelmente aconteceu pq não instalou o captchaReceitaAudio, o que é estranho. Veja se resolve rodando devtools::install_github('decryptr/captchaReceitaAudio')

**Comment by sillasgonzaga** [comment]
Já tá instalado sim.

```
devtools::install_github('decryptr/captchaReceitaAudio')
Skipping install of 'captchaReceitaAudio' from a github remote, the SHA1 (619da1a4) has not changed since last install.
  Use `force = TRUE` to force installation

```
Mesmo eu forçando o R a carregar o capthaReceitaAudio com library(), o erro continua.

**Comment by jtrecenti** [comment]
é culpa do captchaReceitaAudio. Vamos arrumar e aviso
