### ISSUE TITLE
BUG: string de entrada 1 é inválida nesse locale

### ISSUE THREAD

**Issue by racerxdl** [jtrecenti/cnpjReceita#3]
Quando chamo o `buscar_cnpj` com `qsa = TRUE` recebo um timeout do curl e uma mensagem de erro:

```
string de entrada 1 é inválida nesse locale
```

Sem o `qsa = TRUE` eu recebo os dados do CNPJ normalmente.

**Comment by jtrecenti** [comment]
É um problema no site da Receita. 
Na verdade eu preciso melhorar as mensagens de erro pra deixar claro o que é que da pau em cada vez, pois a receita trava de varias formas...
