### ISSUE TITLE
Problema instalação

### ISSUE THREAD

**Issue by brunoavilela** [jtrecenti/cnpjReceita#4]
Não estou conseguindo instalar. Já atualizei o R,mas sem sucesso ainda. As mensagens de erro são as seguintes:

Downloading GitHub repo jtrecenti/cnpjReceita@master
from URL https://api.github.com/repos/jtrecenti/cnpjReceita/zipball/master
Installing cnpjReceita
Downloading GitHub repo decryptr/captchaReceitaAudio@master
from URL https://api.github.com/repos/decryptr/captchaReceitaAudio/zipball/master
Installing captchaReceitaAudio
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Bruno/AppData/Local/Temp/RtmpMdb9lr/devtools7cc5a72497b/decryptr-captchaReceitaAudio-26016b0"  \
  --library="C:/Users/Bruno/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'captchaReceitaAudio' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'captchaReceitaAudio' in namespaceExport(ns, exports):
 undefined exports: baixa_img_audio
Erro: loading failed
Execução interrompida
*** arch - x64
Error: package or namespace load failed for 'captchaReceitaAudio' in namespaceExport(ns, exports):
 undefined exports: baixa_img_audio
Erro: loading failed
Execução interrompida
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Bruno/Documents/R/win-library/3.4/captchaReceitaAudio'
Installation failed: Command failed (1)
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Bruno/AppData/Local/Temp/RtmpMdb9lr/devtools7cc4c4c405e/jtrecenti-cnpjReceita-6a67c07"  \
  --library="C:/Users/Bruno/Documents/R/win-library/3.4" --install-tests 

ERROR: dependency 'captchaReceitaAudio' is not available for package 'cnpjReceita'
* removing 'C:/Users/Bruno/Documents/R/win-library/3.4/cnpjReceita'
Installation failed: Command failed (1)

**Comment by jtrecenti** [comment]
esse pacote tá deprecated.

veja aqui

https://github.com/decryptr/captchaReceitaAudio
